### ISSUE TITLE
Please take all my money

### ISSUE THREAD

**Issue by EvanBalster** [juandagilc/Acapela#1]
Hello —

Chiming in to express my interest in a purchasable version of this gizmo!  I don't have access to the fabrication systems necessary to produce these parts (though I'm sure there are online services) and I would be eager to put together a box like this.

**Comment by juandagilc** [comment]
Hello Evan,
I am glad you would like to have one of this and that you are willing to give me all your money for it XD. Can you contact me by [email](http://juangil.com/about/)?
